# Generated by Django 5.0.1 on 2024-02-04 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0002_add_placeholder_config"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="config",
            options={
                "ordering": ["bluesky_username"],
                "verbose_name": "Bluesky User Configuration",
                "verbose_name_plural": "Bluesky User Configurations",
            },
        ),
        migrations.AddField(
            model_name="post",
            name="error",
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
