# Generated by Django 5.0.1 on 2024-02-04 02:08

from django.db import migrations, models


def migrate_post_status(apps, schema_editor):
    Post = apps.get_model("posts", "Post")
    for post in Post.objects.all():
        is_published = True if post.posted_at or (post.cid and post.uri) else False
        if post.is_draft and post.error:
            post.post_status = "❌ Error"
        elif post.is_draft:
            post.post_status = "📝 Draft"
        elif is_published:
            post.post_status = "✅ Published"
        else:
            post.post_status = f"⏳ Scheduled"
        post.save()


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0004_remove_config_interval_hours_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="post_status",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.RunPython(migrate_post_status),
    ]
