# Generated by Django 5.0.1 on 2024-02-04 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0005_post_post_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="reply_to",
            field=models.ForeignKey(
                null=True, blank=True, on_delete=django.db.models.deletion.CASCADE, to="posts.post"
            ),
        ),
    ]
