# Generated by Django 5.0.1 on 2024-02-06 19:19
# Modified by andyscpalmer

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0006_post_reply_to"),
    ]

    def migrate_images(apps, schema_editor):
        Post = apps.get_model("posts", "Post")

        for post in Post.objects.all():
            if post.image_1:
                if post.image_1.name[:7] != "images/":
                    try:
                        post.image_1.name = f"images/{post.image_1.name}"
                        post.save()
                    except Exception as e:
                        print(f"Error migrating image_1: {post.image_1};\n{e}")
                        post.image_1 = None
                        post.save()
            if post.image_2:
                if post.image_2.name[:7] != "images/":
                    try:
                        post.image_2.name = f"images/{post.image_2.name}"
                        post.save()
                    except Exception as e:
                        print(f"Error migrating image_1: {post.image_2};\n{e}")
                        post.image_2 = None
                        post.save()
            if post.image_3:
                if post.image_3.name[:7] != "images/":
                    try:
                        post.image_3.name = f"images/{post.image_3.name}"
                        post.save()
                    except Exception as e:
                        print(f"Error migrating image_1: {post.image_3};\n{e}")
                        post.image_3 = None
                        post.save()
            if post.image_4:
                if post.image_4.name[:7] != "images/":
                    try:
                        post.image_4.name = f"images/{post.image_4.name}"
                        post.save()
                    except Exception as e:
                        print(f"Error migrating image_1: {post.image_4};\n{e}")
                        post.image_4 = None
                        post.save()
            post.save()

    operations = [
        migrations.AlterField(
            model_name="post",
            name="image_1",
            field=models.ImageField(
                blank=True, null=True, upload_to="images/%Y/%m/%d/"
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="image_2",
            field=models.ImageField(
                blank=True, null=True, upload_to="images/%Y/%m/%d/"
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="image_3",
            field=models.ImageField(
                blank=True, null=True, upload_to="images/%Y/%m/%d/"
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="image_4",
            field=models.ImageField(
                blank=True, null=True, upload_to="images/%Y/%m/%d/"
            ),
        ),
        migrations.RunPython(migrate_images),
    ]
